### PR TITLE
Added login and signup pages

### LINKED ISSUE #5: Design and create a login and registration page.
You can refer the the image below:-
Register
Login

### PR DESCRIPTION
**Pull request by VanshVg**
## Pull Request Description

* Languages used: JavaScript (JSX), CSS
* Approach used: Added two functions (login and signup) to login.jsx, created corresponding CSS styles in login.css, and added a background image in the public folder.
* Question solved: Added login and signup functionality to the project.
* Issue(s) related: #5

## Related Issue

Fixes #5 

## Changes Made

- Added login and signup functions to login.jsx for login and signup functionality.
- Created corresponding CSS styles in login.css for the login and signup components.
- Added a background image in the public folder for improved visual design.

## Checklist

- [x] The code follows the project's code guidelines
- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated, if applicable
- [x] All linting errors and warnings have been resolved
- [x] The code has been tested locally and works as expected
- [x] No new dependencies have been introduced without proper justification

## Images

login

signup

## Note
- Please add href attribute inside anchor tags in both login and signup according to relevant route.

### CODE REVIEW

**Comment by Aishika3** [comment]
For the smooth transition of the pages modify the code as follows:-
1.Make a signup.jsx page in the same folder that in the login.jsx.
2.In the login.css file attach the image in form of drive link.
Make the following changes make the pr again.

**Comment by Aishika3** [comment]
Hint for the login.jsx:-
login jsx
Hint for signup.jsx:-
Signup
Signup jsx

**Comment by Aishika3** [comment]
also make the required changes for the login.css as but above part remain same as it it was:-
css

**Comment by VanshVg** [comment]
Hey can you please tell me why have you used state here to show login??
I mean we can directly create two different components and provide Routes for each and we can add Link tag at "Already an user? Login"/ "New user? Signup" to corresponding routes right?

**Comment by Aishika3** [comment]
When I was importing any of the pages from the app.js section then it was showing error and even the link was not working.You can use react router and through Link tag you can link to other pages but here I did it because only some part of the section was changing in the login and signup pages and afterwards when we will add the verification part that time it will become easy.

**Comment by VanshVg** [comment]
Ok Got it !

**Pull request closed without merging**
